### ISSUE TITLE
Testing - Charge

### ISSUE THREAD

**Issue by rravenhill** [jaymedavis/stripe.net#100]
Hi, Demo shows code to create a charge. Testing using sample as is results in the following exception.

{"Invalid string: {\"number\"=>\"424242******4242\", \"exp_month\"=>\"10\", \"exp_year\"=>\"2016\"}"}

Any idea why?

Thanks
Richard

**Comment by StefanMilne** [comment]
Thanks jcharters.... I fell into this trap too.

**Comment by jaymedavis** [comment]
reopening this to get this in the readme. To be clear, on charges, you can specify card or customer, but not both - I could swear this used to be in the readme, i must have goofed up and removed it at some point.

**Comment by StefanMilne** [comment]
Hi sorry Jayme, didn't realise me commenting automatically reopened this. I am new to Stripe and since the new release of Stripe.net my testing ground was tweaked a little and I am trying to get to grips with it. I am working on a project which supports subscriptions and purchases(hardware) with the 2 being inclusive or exclusive. My logic is to create the subscription first (if needed) then use the stripecustomerid for the charge again if needed. If the user only purchases lets say hardware... I need to create a stripe customer, add a card and then create the charge... Is that correct or is there a better more efficient way?

**Comment by jaymedavis** [comment]
No worries, you didn't actually re-open it, I did. :) ... I wanted to make sure I got this in the readme. 

That sounds fine to me. The only thing I would be aware of, is you might want to use the stripe javascript library to pass over the card details and then get a token back. That will make sure you are PCI compliant (not passing credit cards through your servers).

**Comment by StefanMilne** [comment]
hmm interesting - thanks for that
