### ISSUE TITLE
Stripe.StripeCustomer.Deleted' is obsolete: 'This property is not documented and could be removed in a later release.'

### ISSUE THREAD

**Issue by xavierjohn** [jaymedavis/stripe.net#305]
Deleted property is not obsolete and it is documented at
https://stripe.com/docs/api#retrieve_customer
"When requesting the ID of a customer that has been deleted, a subset of the customer's information will be returned, including a "deleted" property, which will be true. 
"

**Comment by jaymedavis** [comment]
I do not see it on my version of the API. What version are you running (you can find out logging into your account and going to settings).

**Comment by jaymedavis** [comment]
I've asked stripe support to comment on this one - it may just be missing from the documentation and I need to remove the obsolete attribute. Thanks for bringing this up!

**Comment by jaymedavis** [comment]
From Stripe:

I think this is definitely expected and here to stay as far as I can tell so that's something you can safely add to Stripe.NET I think. We don't document all the properties on our objects to avoid confusing users too much and since that property only appears when you retrieve a deleted customer we added the note in the Retrieve Customer API documentation.

I hope this helps but please do not hesitate to get back to me if you need more details.
All the best,
Thomas

So I will remove the obsolete attribute - thanks for bringing this up.

**Comment by xavierjohn** [comment]
Cool, thanks. 

I got my Stripe integration done thanks to your module and Stripe.Webhooks.Module. https://github.com/rbwestmoreland/stripe.webhooks.module
