### ISSUE TITLE
all of the tests don't pass out of the box

### ISSUE THREAD

**Issue by jaymedavis** [jaymedavis/stripe.net#306]
the transfer tests fail on new accounts because there are insufficient funds in stripe. You can reproduce this by running all of the tests after deleting all of your stripe test data, or creating a new account. It probably will just be setting up some initial test to run to make sure funds are present.

**Comment by jaymedavis** [comment]
You should be able to clone the repo, compile it in debug mode, add your test key to app.config under Stripe.Tests, and have all tests pass.

**Comment by Giovani-Brady** [comment]
the transfer tests failing because of insufficient funds can be fixed by changing the charge test to use credit card number: 4000000000000077

charging this card will bypass the pending balance and make the fund immediately available for transfer. this should only be used for unit testing purposes as the change to the API was made to mimic the live environment as much as possible.

**Comment by jaymedavis** [comment]
is it seriously that simple? lol

**Comment by Giovani-Brady** [comment]
yeah, i thought there was a way to order the way the test were run so the charge test could for sure run always before the transfer test.

**Comment by jaymedavis** [comment]
easy $20 for someone. :)

**Comment by Giovani-Brady** [comment]
issues addressed in #321

**Comment by kpeoples** [comment]
Does anyone have any code examples of writing unit test in C# for using Stripe.Net.  I think my cold medicine is clouding my mind and I cannot figure it out.
