### ISSUE TITLE
Building with older version of Newtonsoft

### ISSUE THREAD

**Issue by jaime-fuhr** [jaymedavis/stripe.net#335]
My project has a 3rd party DLL that is using version 3.5.0 Newtonsoft.JSON which won't work with the latest version of Stripe.net.

I opened the source and changed the reference from the 6.0 version to 3.5.   Everything builds except for one line in ExpandableProperty.cs:

                T item = ((JToken)value).ToObject<T>();

The older version does not have the method ToObject<> in the JToken class.

Any thoughts on this or a work-around?

Thanks!
Jaime

**Comment by jt000** [comment]
I'd suggest contacting the 3rd party and getting them to upgrade to the latest version. There are a lot of fixes since 3.5 & it would be safer security-wise to have them upgrade then down-grade stripe.net. Plus, the [last 3.5 release was Aug 2010](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/3.5.8), so they're due for an upgrade anyway... :smile:

Alternatively, rather than downgrading Stripe.NET, assuming there aren't any breaking changes (which I'd be very surprised if there weren't any) then you might be able to do a [binding redirect for the 3rd party assembly](https://msdn.microsoft.com/en-us/library/7wd6ex19%28v=vs.110%29.aspx) so it will load the 6.0 version of Json.NET.

**Comment by jaime-fuhr** [comment]
Unfortunately the 3rd party developer went out of business and we stuck with using their control until we can find a replacement.  Chat client.

I'll try the binding redirect and give that a go.  

Thanks for posting!

**Comment by jaime-fuhr** [comment]
jt00, thanks for your help.  The binding redirect worked perfectly.   I used the solution found in here http://stackoverflow.com/questions/17236342/newtonsoft-json-assembly-package-version-mismatch
