### ISSUE TITLE
Upcoming Invoices

### ISSUE THREAD

**Issue by dwthomson** [jaymedavis/stripe.net#336]
I am trying to preview an invoice so that I can show the user what they will be paying before I update their invoice.

The stripe API says you can add a new plan id to the upcoming function, but can't see to with stripe.net
https://stripe.com/docs/api/go#retrieve_customer_invoice

Am I missing something or is this something that is going to be added?

**Comment by jt000** [comment]
Seems like the API is missing the additional arguments. Could possibly use a ```InvoiceUpcomingOptions``` for ```InvoiceService.Update()``` instead of just the nullable SubscriptionId parameter.

**Comment by jaymedavis** [comment]
I typically go with the convention of required parameters being passed as arguments, and everything else being passed in an optional object.

So the new signature of this method should be (when complete)-
public virtual StripeInvoice Upcoming(string customerId, UpcomingInvoiceOptions upcomingOptions = null)

A new UpcomingInvoiceOptions object should be created with the new (since initial development) parametersl. This would be great to have before 3.0 is released since it will be a breaking change to that signature. PR welcome! :)

**Comment by jdc0589** [comment]
+1. run in to a case where I need this. Anyone started work on it yet?

**Comment by jdc0589** [comment]
On this topic... there is a SUPER undocumented, but supported parameter for working with billing cycle anchors + the upcoming invoice api method, which should probably be supported: `subscription_billing_cycle_anchored_at`

**Comment by jaymedavis** [comment]
This one is related to #354. I left a comment there - but in short, customerId is required - so I'd like to have that, then UpcomingInvoiceOptions as an optional param. However, we could just make the new signature for now, and I can deprecate the existing one for the next version (the existing one has subscriptionId which can move to UpcomingInvoiceOptions)

**Comment by jaymedavis** [comment]
Closing - this was implemented a long time ago.
