### ISSUE TITLE
windows phone 8.1 support?

### ISSUE THREAD

**Issue by mlowitz** [jaymedavis/stripe.net#337]

**Comment by jt000** [comment]
Is the request to have this entire api ported to a windows phone compatible dll? Or are you asking to have a [Stripe.js](https://stripe.com/docs/stripe.js)\[checkout](https://stripe.com/docs/checkout) equivalent API for Windows Phone?

**Comment by mlowitz** [comment]
have stripe.net  made windows phone compatible as there is currently no
stripe api thats compatible with windows phone8.1

On Mon, May 18, 2015 at 5:35 PM, Jason Tremper <notifications@github.com>
wrote:

> Is the request to have this entire api ported to a windows phone
> compatible dll? Or are you asking to have a Stripe.js
> <https://stripe.com/docs/stripe.js>[checkout](
> https://stripe.com/docs/checkout) equivalent API for Windows Phone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaymedavis/stripe.net/issues/337#issuecomment-103219374>
> .
>



-- 

-Morris

**Comment by jt000** [comment]
I don't think you'd want to put this API on any client platform. In order to use this API the system has to have the [Secret Key](https://support.stripe.com/questions/difference-between-secret-key-and-publishable-key), which has the ability to perform all actions on your account (including initiating transfers , refunds, & setting account settings). I wouldn't suggest making that key accessible to a client where it can fall in the wrong hands...

However, I could see some value in creating a [Stripe.JS](https://stripe.com/docs/stripe.js) or [Checkout](https://stripe.com/docs/checkout) equivalent for .NET, which only uses the publishable key. AFAIK, there isn't a .NET API for this that I know of...

**Comment by jaymedavis** [comment]
It seems like having your secret key on a client device could be really, really bad. I would definitely not do that.

Just off the top of my head, you could implement a server side implementation of your app that uses stripe.net as well. Your client could make calls to your server, and you could process information that way. Remember to keep PCI compliance in mind, though, you don't want to pass the CC# this way., so you would need a Stripe.JS implementation. This may not be the best option, but something to think about. :)
