### ISSUE TITLE
One time charge getting "Must provide source or customer id" error response

### ISSUE THREAD

**Issue by rkrubeck** [jaymedavis/stripe.net#340]
I'm using the latest version of Stripe.net (nice API by the way!), my version of the stripe api on my stripe dashboard is 2013-08-13 (if that matters which I doubt that it does).  I get the error noted in the subject line above with the code below (I get a valid tokenID back from a javascript call to stripe prior to invoking this c# method).  Any clues to what I'm doing wrong?

StripeChargeCreateOptions oneTimeCharge = new StripeChargeCreateOptions();

oneTimeCharge.Amount = 13900;
oneTimeCharge.Currency = "usd";
oneTimeCharge.Description = "New purchase";
oneTimeCharge.Card = new StripeCreditCardOptions();
oneTimeCharge.Card.TokenId = viewModel.StripeToken;
           
 StripeChargeService chargeService = new StripeChargeService();
StripeCharge stripeCharge;
 try
{
                stripeCharge = chargeService.Create(oneTimeCharge);
}
catch (StripeException se)
 {
                // Declined or some other problem.  Return message to the user.
                viewModel.ErrorMessage = se.Message;
                return;
}

**Comment by jaymedavis** [comment]
Did you ever create a StripeCustomer? If so, you will need to set the CustomerId on oneTimeCharge.

**Comment by spiez** [comment]
I'm having the same issue, I don't want to use StripeCustomers. The fact is that stripe uses the "source" parameter to pass the TokenID. How can I solve this? https://stripe.com/docs/tutorials/charges

**Comment by jt000** [comment]
There is a [test for this case](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe.Tests/charges/when_creating_a_charge_with_a_token.cs), which passes for me. I'm not sure what is different in your situation other than the API key (which might have an impact if Stripe is attempting to look for ```source```). Try changing the API key to "2015-02-10" and see if that has an impact.

Otherwise, you could attach a debugger & put a breakpoint at [GetWebRequest](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Infrastructure/Requestor.cs#L40) to verify that there is a proper "card[tokenid]" parameter in the url.

**Comment by spiez** [comment]
I'm not able to change the API key from the account settings in stripe, I've even created a brand new account and it stated "API version will be automatically chosen when you make the first API usage", so I did a Stripe.NET connection and it chose " 2015-04-07 (latest)". So I'm pretty stuck right now.

**Comment by bleigh00** [comment]
@spiez  he how were able to solve the problem with JS file sending a null token string. i am having the same issue. I don't believe my Js file is parsing the info
