### ISSUE TITLE
Dispute Structured Evidence

### ISSUE THREAD

**Issue by toddca** [jaymedavis/stripe.net#342]
How do you submit structured evidence for a dispute?

ref: https://stripe.com/docs/guides/dispute-evidence

I can see there is a dispute update method that accepts a single string however the example just shows a simple message/comment type of string being passed. Am I just missing this somehow?

**Comment by toddca** [comment]
Also looking for a way to upload dispute information via file uploads. Cannot seem to find that in this API either.

**Comment by jaymedavis** [comment]
The information you linked to for dispute just needs to be added. When Stripe discount was implemented, that did not exist at the time. StripeDisputeCreateOptions or something like that probably needs to be implemented based on your link.

File uploads has not been developed yet.

**Comment by jeancroy** [comment]
+1 for File uploads

If it help anyone I was able to make it works using the same HttpClient/HttpRequestMessage infrastructure as stripe.net. A lot of what is on the net use the lower level stuff.

https://gist.github.com/jeancroy/c71f8a710734a7d13248f968c778d428

**Comment by jaymedavis** [comment]
Thanks for posting this, it looks less complicated than the other solutions I've seen. Ill definitely keep as a reference - thanks!

What platform are you on? I'm wondering if there's any chance that could work with mono (thinking no because of async - will probably have to roll two versions).

**Comment by jeancroy** [comment]
Hi @jaymedavis 

Basically I followed your model.

Here you create a HttpRequestMessage and set the content property.
https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Infrastructure/Requestor.cs#L120-L123


Here I create a HttpRequestMessage 
https://gist.github.com/jeancroy/c71f8a710734a7d13248f968c778d428#file-multipartupload-cs-L6

and set the content property
https://gist.github.com/jeancroy/c71f8a710734a7d13248f968c778d428#file-multipartupload-cs-L34

Main difference is that I use a fancy MultipartFormDataContent instead of your StringContent
https://gist.github.com/jeancroy/c71f8a710734a7d13248f968c778d428#file-multipartupload-cs-L9

---

So to answer your question I use a standard asp.net 4 mvc 5 application.
Most of the async stuff should be similar to yours

The special part may be in MultipartFormDataContent and there seem to have a mono implementation here
https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http/MultipartFormDataContent.cs

**Comment by toddca** [comment]
I submitted a pull request for this back in March.

**Comment by jeancroy** [comment]
Indeed your PR #469 take the same approach and is better integrated

**Comment by jaymedavis** [comment]
File Uploads has been out - just cleaning up. Re-open if there is still an issue.
