### ISSUE TITLE
StripeAccountService No update and Delete methods available.

### ISSUE THREAD

**Issue by lokopinagar** [jaymedavis/stripe.net#400]
I am using your library but i am in need to update and delete accounts on stripe but their is no method available. Please provide us the code how to do it.

Thank you for your wonderful work

**Comment by jaymedavis** [comment]
There is currently an open PR to handle creating accounts. This work is similar, but a little more involved/lengthy. I will get to it at soon as possible. If you need it expedited, shoot me an email. I'll leave this open so it stays on the radar.

**Comment by BrianRSI** [comment]
Can you point me in the right direction for this? We love this library, but updating/deleting charges is a necessity for us. Is there a workaround, or is this feature in the pipeline. Thanks!!

**Comment by BrianRSI** [comment]
Its the StripeChargeUpdateOptions that is missing

**Comment by jaymedavis** [comment]
This issue is for account updating/deleting, which is the work I am currently working on (managed accounts goes along with this). If you have something missing from charges, please make sure an existing issue doesn't exist, and then open a new one - please be detailed with what you need. :)

I am closing this issue as account management is currently being handled and managed via another PR.
