### ISSUE TITLE
Updating Subscription with TrialEnd = null should not end trial

### ISSUE THREAD

**Issue by maozh** [jaymedavis/stripe.net#405]
When I update a subscription during its trial period, I have to set the TrialEnd property to the original date, otherwise it updates the subscription and ends the trial.
This mean I have to call Get subscription to retrieve this date, which is time consuming!

If I call the Stripe API update method and don't send the trial_end field - it keeps the date! This should be exactly the case if I leave TrialEnd property null!

**Comment by jaymedavis** [comment]
This is by design. If you don't send the property, there is nothing to update. If it were left null and stripe.net sent something to account for that, it would wipe the trial date on current subscriptions for anyone that ever updates anything. This is why it's like this in Stripe (not a feature of stripe.net)

**Comment by maozh** [comment]
But I don't send the property and it DOES update this field. This is what I'm complaining about.

**Comment by jaymedavis** [comment]
Oh my mistake - I read this wrong. Do you want to see how stripe handles this on their end? Since you aren't sending anything and that is happening, that is the design from stripe - I would contact them.
