### ISSUE TITLE
Allow setting proxy settings

### ISSUE THREAD

**Issue by lukencode** [jaymedavis/stripe.net#450]
We some issues using the library due to our internal proxy.

It would be useful to provide proxy settings (perhaps through the StripeConfiguration class) to be used when creating the HttpWebRequest.

**Comment by jaymedavis** [comment]
This is actually changing to HttpClient due to multiple platforms (see the portable branch). I'll leave this issue open so this can be addressed. Can you give me any additional information about what information you would expect to provide?

**Comment by lukencode** [comment]
I've actually managed to solve this at a server level but in other libraries we have passed in a WebProxy instance with the correct credentials.

**Comment by jaymedavis** [comment]
Luke - I'm glad you've got this fixed (with a workaround). For now, it's not really pressing and nobody else has mentioned having this issue. It's not a won't fix, it's just not a priority since you have a workaround and nobody else has spoke up. This may change in the future, but I'm going to close this for now.

**Comment by rmariotti-choicelunch** [comment]
@jaymedavis - first off; Stripe.NET is amazing and really has helped us integrate subscriptions into our lunch ordering platform.  THANK YOU.

I'm trying to see how I could update my Stripe.NET code to send requests **through a proxy**.

We're moving to a more secure environment that requires outbound calls from the API server to pass through a proxy. This way, the outbound proxy can whitelist the Stripe URL in order to allow us to transmit credit card numbers to Stripe but any other target URL would have any detected credit card data rejected.  

Without the ability to configure Stripe.NET through a Proxy, I won't be able to use Stripe.net and resort to manual API calls...no good!

Thank you for helping me understand how I could accomplish this!

Ryan

**Comment by jaymedavis** [comment]
Need to figure out what is needed here. I will do some research on the HttpClient to see if passing proxy settings is possible. 

I'll figure this out if you send me some lunch :)

**Comment by rmariotti-choicelunch** [comment]
haha @jaymedavis - happy to hook you up with a Choicelunch if you're near any of our CA-based kitchens :)  Thanks for taking a look.

**Comment by jaymedavis** [comment]
:)

Actually - you might be able to do this yourself. In Stripe.net, you can pass your own message handler. ```StripeConfiguration.HttpMessageHandler = myHandler``` -  to build that object, look at the answer here: http://stackoverflow.com/questions/29856543/httpclient-and-using-proxy-constantly-getting-407.

After you have that class, I think you can pass it as is. If not, it may require that StripeConfiguration supports having another type you can set - I'm not familiar with this enough yet. If that's the case, I can fix it. 

Let me know if this makes sense. I could build one behind the scenes, but it might be a bit more difficult due to the wide range of platform support in stripe.net (.net core only support IWebProxy).

**Comment by rmariotti-choicelunch** [comment]
Ah; nice.  I'll try that.  It does look like that will work since Requestor.cs uses it (when present) to setup the HttpClient:

`new HttpClient(StripeConfiguration.HttpMessageHandler)`

It'll be a bit until I can test it but thanks for the info @jaymedavis!

**Comment by jaymedavis** [comment]
You're very welcome! Re-open this if it's still an issue and you need another type on StripeConfiguration to pass in to the Requestor.

**Comment by rahulhamdapurkar** [comment]
Following code worked for me, might help someone.

`var proxy = new WebProxy(proxyserver, port);
proxy.Credentials = CredentialCache.DefaultCredentials;
var webRequestHandler = new WebRequestHandler()
{
      UseProxy = true,
      Proxy = proxy,
      UseCookies = false
};
StripeConfiguration.HttpMessageHandler = webRequestHandler;`

-Rahul
