### ISSUE TITLE
Upgrading api versions

### ISSUE THREAD

**Issue by niemyjski** [jaymedavis/stripe.net#466]
I'm currently on `2013-12-03` and I just upgraded the api client from v3 to v6.. I see in your configuration that you are supporting the 2015-07 version. Is it safe to click the upgrade api version in the stripe api settings?

**Comment by niemyjski** [comment]
I just contacted them and asked them to change the api version.. Is there any chance you will support the latest version soon? It would make it easier for people to upgrade major versions of this client.

**Comment by jaymedavis** [comment]
Yes it is. I actually have my account set to the latest version in Stripe, as Stripe.net supports a lot of the new features, it just doesn't sport the title. Stripe.net will force your API version to use the version in StripeConfiguration - it doesn't matter what you set your dashboard too.

The only thing you need to watch out for is web hooks. If you use web hooks, you need to email Stripe and ask them to set your API version to the version in Stripe.net - and even then, only do that if you have issues.

Regarding update the API version:

At the top of the readme, I have the next goals laid out. In addition to this, I'm about to release a version that uses the post body instead of the URL (makes error messages a lot more accurate). In parallel with that, I'm working on Async functionality in the library, and upgrading the API. Thanks for noting your concern as that helps me prioritize getting this upgraded.

**Comment by niemyjski** [comment]
Yes, we use web hooks in our app.

**Comment by niemyjski** [comment]
That's awesome! Thanks for all of your help!

**Comment by jaymedavis** [comment]
Then you should be set after emailing them - I re-opened this so I could tag it as one that's in progress. I'll just close this when it's upgraded. :+1: 

No problem!
