### ISSUE TITLE
Stripe.net compatibility with .NET version

### ISSUE THREAD

**Issue by AlexNZen** [jaymedavis/stripe.net#494]
Is stripe.net 6.0+ backward compatible with .NET 4.0? Please clarify. Thanks a lot.

**Comment by jaymedavis** [comment]
No, 4.5+.

**Comment by ensemblebd** [comment]
really... forcing 4.5 just for async's....

**Comment by xt0rted** [comment]
It's also because of TLS 1.1 which is only available in 4.5+ https://stripe.com/blog/upgrading-tls

**Comment by ensemblebd** [comment]
Ah ok. Well, guess it's time to upgrade all the projects on the server then. Since 4.5 overwrites things in 4.0.
I'm assuming others will be here soon as well, since Stripe is sending out notices of dropping TLS 1.0 support in january 2017.

For any other passerby's, there's apparently a magical thread somewhere in here where the creator helped someone find the most recent version that supports 4.0, or so he said. I couldn't find it.
So I tried the minimum required version according to Stripe, 5.1.2. And it doesn't seem to work properly when building the project, which seems to jive with the experiences of others. Where the project doesn't specifically say it requires 4.5, and yet it does.
Save yourself some time, and just convert to 4.5.

**Comment by jaymedavis** [comment]
Thanks @xt0rted. This is misunderstood by a lot of 4.0 users that Stripe is going to turn them off. :)

The thread was in my email. This project has a lot of users, so I can't recall all of my conversations. The user I talked with upgraded to 5.3.0. 

@ensembledbd there's no need to be rude. Please keep in mind you are using free open source software, and you have the ability to change code and fork as you see fit according to the Apache license.

**Comment by ensemblebd** [comment]
Fair enough, my apologies. I'm sure you can understand the day to day frustrations.

**Comment by AlexNZen** [comment]
Hello! 
We haven't touched our Webapp which is based on Checkout.js and Stripe.NET on .NET 4.0 since 03/2016 (it works just fine). Now we have to revisit because of TLS 1.2. 
Unfortunately it's not clear how section from to the above email
Ref [https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2#dotnet](url) related to Stripe.NET:
"Connect applications
If your Stripe integration is entirely controlled by a Connect application, they will be taking these updates on your behalf. You will not need to do anything to upgrade your integration." 

Any help would be highly appreciated!
Thanks in advance,
Alex
