### ISSUE TITLE
Exceptions thrown for declined payment

### ISSUE THREAD

**Issue by tunwin819** [jaymedavis/stripe.net#498]
A suggestion, that instead of throwing a `StripeException `when a payment is declined for a `StripeCharge`. Perhaps change the:

`public virtual StripeCharge Create(StripeChargeCreateOptions createOptions, StripeRequestOptions requestOptions = null);`

to

`public virtual StripeCharge Create(StripeChargeCreateOptions createOptions, out StripeChargeResponse response, StripeRequestOptions requestOptions = null);`

The out parameter being a new Class of `StripeChargeResponse`.

I have always been taught that you shouldn't rely upon an Exception for the normal flow of code. Plus this allows for a strongly typed error/success response, instead of the generic `StripeException`.

**Comment by jaymedavis** [comment]
This is interesting. The problem with doing this, is I follow everything Stripe does without any custom logic of my own whenever possible. In this case, I believe Stripe is actually the one throwing the exception, so I would be hiding that from the user to implement my own way of handling this. If this doesn't make sense, please reopen and feel free to comment more! Appreciate the feedback.

**Comment by tunwin819** [comment]
For a declined payment it actually returns a 402 HTTP Response. I would think only 5xx responses should throw exceptions.

200 - OK 	Everything worked as expected.
400 - Bad Request 	The request was unacceptable, often due to missing a required parameter.
401 - Unauthorized 	No valid API key provided.
402 - Request Failed 	The parameters were valid but the request failed.
404 - Not Found 	The requested resource doesn't exist.
409 - Conflict 	The request conflicts with another request (perhaps due to using the same idempotent key).
429 - Too Many Requests 	Too many requests hit the API too quickly.
500, 502, 503, 504 - Server Errors 	Something went wrong on Stripe's end. (These are rare.)

If I get some time, I may do the pull request myself and add some polymorphic methods to the existing ones and a `StripeChargeResponse` class. I think deprecating the existing methods at this stage would cause a lot of people problems.

**Comment by jaymedavis** [comment]
I think the problem here is really in the naming. StripeException means something went wrong on Stripe's end, no matter what it is. Something other than a successful call. It was really done for simplicity so all service calls can be wrapped in a try/catch(StripeException). Yeah - something changed with this is a really fundamental change in the library.

**Comment by tim-schmidt** [comment]
@grant-unwin and @jaymedavis I'd like to propose this be reopened. I'm receiving this for validation errors like incorrect CVV or Postal Code.

The Stripe .NET SDK is the one throwing the exception, [here, if I'm not mistaken](https://github.com/stripe/stripe-dotnet/blob/3ca9fee8c8672e7768a448c49a5575e15475fa83/src/Stripe.net/Infrastructure/Public/StripeClient.cs#L157-L164). But the Stripe API responded with a 402 ERR

Error message
```
"message": "The zip code you supplied failed validation."
"type": "card_error"
```

So, it's just not mapping and responding correctly? If I were using a custom HttpClient and hitting the API directly, I'd receive a 402 from Stripe's API, bubble it up to those calling my API, they'd get the message, and be able to respond appropriately. However, since the Stripe .NET SDK is throwing a 500, it is misleading.

When I make other requests that have a missing parameter, or a value beyond bounds, I don't get a 500, I get an appropriate 400-series, so why this one? I mean, it literally says it's a validation error ;)

Now I'll have to write code to trap an error that was already trapped, write logic to parse out if it was REALLY an exception or validation error, then pass it back up...but only in certain situations.

Sorry if I sound frustrated. I just spent several hours tracking this down.

**Comment by remi-stripe** [comment]
@tim-schmidt This is an issue that is over 7 years old and the library has drastically changed over the years. The case you describe would definitely raise a 402 that you could catch and handle as expected, it would not rase a 500 which only happens when there's a real crash in our API. 

I would highly recommend that you work directly with our support team so that they can look at the API requests you are making, your exact code and guide you towards the best integration path/workaround that could work for you.
You can contact them here: https://support.stripe.com/contact

**Comment by tim-schmidt** [comment]
@remi-stripe OMG, I just noticed 'Apr 26' and not the year. Sorry for the necro-bump.

I'll check with my support team. Thanks!
