### ISSUE TITLE
StripeEvent.UserId always null

### ISSUE THREAD

**Issue by TravyDale** [jaymedavis/stripe.net#532]
I am handling webhook events and I noticed my UserId property is always null. Is there a reason why that it?

**Comment by jaymedavis** [comment]
Most likely, you need to contact Stripe and have them set your Version to the same date in StripeConfiguration.cs

**Comment by scottndecker** [comment]
This happens for me as well.  I just checked and both of my API versions are set to '2016-07-06'.  I receive the event json, then call StripeEventUtility.ParseEvent(json) and the result of that has a UserId of null

**Comment by jaymedavis** [comment]
Can you debug and show me the exact json that is coming from the event? This might be an issue of the entity not matching the payload.

**Comment by scottndecker** [comment]
Changed the subscription and customer id's just to be on the safe side but here it is:
"{
  \"id\": \"evt_18sOR3C1FMomZybqScmysatw\",
  \"object\": \"event\",
  \"api_version\": \"2016-07-06\",
  \"created\": 1473563713,
  \"data\": {
    \"object\": {
      \"id\": \"sub_1234abcd\",
      \"object\": \"subscription\",
      \"application_fee_percent\": null,
      \"cancel_at_period_end\": false,
      \"canceled_at\": 1473563713,
      \"created\": 1473563650,
      \"current_period_end\": 1473736450,
      \"current_period_start\": 1473563650,
      \"customer\": \"cus_5678wxyz\",
      \"discount\": null,
      \"ended_at\": 1473563713,
      \"livemode\": false,
      \"metadata\": {},
      \"plan\": {
        \"id\": \"Dev-VTS-Daily\",
        \"object\": \"plan\",
        \"amount\": 499,
        \"created\": 1473561272,
        \"currency\": \"usd\",
        \"interval\": \"day\",
        \"interval_count\": 1,
        \"livemode\": false,
        \"metadata\": {},
        \"name\": \"Dev-VTS Daily Subscription\",
        \"statement_descriptor\": \"Dev-VTS-Daily\",
        \"trial_period_days\": 2
      },
      \"quantity\": 1,
      \"start\": 1473563650,
      \"status\": \"canceled\",
      \"tax_percent\": null,
      \"trial_end\": 1473736450,
      \"trial_start\": 1473563650
    }
  },
  \"livemode\": false,
  \"pending_webhooks\": 1,
  \"request\": \"req_9AjuPa0frA9JVL\",
  \"type\": \"customer.subscription.deleted\"
}"

**Comment by jaymedavis** [comment]
Can you post your full code? I don't see any user ID in this response - not sure how you are trying to map it? Which object is user ID null on?

**Comment by scottndecker** [comment]
Here is the full snippet of code.  It's the webhook on the app.  So all event get passed to this endpoint and then it handles them appropriately from there.  The event above is a subscription cancellation, so I would expect the customer info to be on it when I StripeEventUtility.ParseEvent.  You can see the "customer" string is on the raw json that's POSTed into the endpoint, but it doesn't end up on the User Id.  Am I misunderstanding how that all works?

Here is the webhook endpoint:
[HttpPost]
        public async Task<ActionResult> ProcessStripeEvent()
        {
            var json = new StreamReader(Request.InputStream).ReadToEnd();

            var stripeEvent = StripeEventUtility.ParseEvent(json);

            var isRealEvent = VerifyEvent(stripeEvent.Id);

            //the next line tries to get the user from my db, but it won't work because UserId is always null
            var user = UserManager.Users.FirstOrDefault(u => u.StripeCustomerId == stripeEvent.UserId);

            ....go do stuff
        }

**Comment by scottndecker** [comment]
Any update on this?

**Comment by jaymedavis** [comment]
Check out the readme in the events section, you are missing a bit of code. The StripeEvent object that is returned is more of a metadata object for the event. In this case, the object property is a subscription, so you need to map that to a subscription object - something like:

var subscription = Stripe.Mapper<StripeSubscription>.MapFromJson(stripeEvent.Data.Object.ToString());

At this point, you have the subscription, and should be able to grab the CustomerId from there. 

The way Stripe.net works is simply mapping that response you pasted to entities by name. Generally speaking, they are the same name. UserId is not populated because it is not in the payload that you pasted coming back. Make sense?

**Comment by scottndecker** [comment]
Got it.  That missing lined helped greatly.  Only I had to change was to strongly type it as a StripeSubscription so that I could use the properties thereof.

StripeSubscription stripeSubscriptionDeleted = Stripe.Mapper<StripeSubscription>.MapFromJson(stripeEvent.Data.Object.ToString());

Thanks for the help!
