### ISSUE TITLE
Api calls failing below api level 23

### ISSUE THREAD

**Issue by SShaw1985** [jaymedavis/stripe.net#621]
Hello

I am attampting to use the ListAsync method to get a list of customers from stripe.

This works perfectly on my Galaxy 6 with an os of API level 23.

However if i use a device with and api level < 23 i get a 401 response back from stripe.

the request content is the same for both so im wondering if there might be a bug somewhere or perhaps something im not seeing

Thanks
Stephen

**Comment by SShaw1985** [comment]
This was all happening because

**Comment by jaymedavis** [comment]
That was going to be my guess - they were telling you unauthorized because of that. Stripe.net has an undocumented feature where you can set `StripeConfiguration.HttpMessageHandler` to another handler - you can read more about this [on this issue](https://github.com/jaymedavis/stripe.net/issues/567).
