### ISSUE TITLE
Is Stripe's Radar supported?

### ISSUE THREAD

**Issue by mnys2016** [jaymedavis/stripe.net#654]
Not sure if Radar and custom rules are supported by Stripe.Net

**Comment by jaymedavis** [comment]
Nope - this is pretty new to my knowledge. I will need to start this implemented. Any help/advice/PRs are welcome.

**Comment by duckwaffle** [comment]
Just trying to get my head around this, with the new version of the SDK, are all charges made using the SDK now valid for Radar? Got someone asking for it internally, and I was wondering if there is anything that I need to do except update the package heh.

**Comment by jaymedavis** [comment]
What version are you on now? Check the [release notes](https://github.com/jaymedavis/stripe.net/releases) from your version to current. I have a new repo I am testing for migrating the library to .net core, which I could give you a nuget package you could add locally. If you're available to help try it out, I'd appreciate it. If not, it will be coming up soon - I recommend keeping Stripe.net up to date - as I try to make releases pretty easy on users release to release. I have only introduced minor or no breaking changes in 6.x.

**Comment by duckwaffle** [comment]
Our production app is using a slightly modified version of 6.4.0, which I can see is juuuuust before you updated everything to use the latest version of the API. I'm assuming that that is the main reason why charges are showing up as unsupported by Radar.

We try not update packages too often because releasing a new version of a production mobile application is a pain in the ass, but we have a major update coming out very soon so I will probably take the time to update this one so it can piggyback on some UAT time, especially since it will add support for Radar stuff.

Appreciate the offer to try out the netcore version, but it would be unlikely that we would get approval to use a pre-release library for payment  processing :P Will definitely keep my eye out for it though!

**Comment by jaymedavis** [comment]
> Appreciate the offer to try out the netcore version, but it would be unlikely that we would get approval to use a pre-release library for payment processing :P Will definitely keep my eye out for it though!

Hahaha! I didn't think of it this way, but I totally understand. Please do let me know how your upgrade goes.
