### ISSUE TITLE
Newtonsoft.Json Dependency Error

### ISSUE THREAD

**Issue by eigenheerc** [jaymedavis/stripe.net#697]
This is in regards to ticket #694 I still get the same error. I've tried the suggestion but to no avail. Would you kindly point me in the right direction? Thanks. Chris

**Comment by jaymedavis** [comment]
What platform are you using? OS?

**Comment by eigenheerc** [comment]
dev is on win7, sql 2008r2, prod is win2008 server, sql2008r2. i'm using vs express 2013.

**Comment by me-tim** [comment]
I am having the same problem.  This is preventing me from joining the project which I am very interested in.  My configuration is: Win 10 Home, VS Community 2013 update 4, .net 4.5  Below is a screenshot of error message from VS Manage Nuget Packages screen:
"
![image](https://cloud.githubusercontent.com/assets/24681799/21358678/0db08190-c69f-11e6-82af-0bacca1c7bda.png)

**Comment by jaymedavis** [comment]
[install the latest nuget package manager](http://stackoverflow.com/questions/25725545/nuget-x-already-has-a-dependency-defined-for-y)

see if that fixes it - I'll get a note in the readme if so.

**Comment by eigenheerc** [comment]
Installed nuget package manager and upgraded stripe.net to v7.0.0 with no apparent issues. Thank you!!!

**Comment by me-tim** [comment]
I also installed the latest nuget package manager and I was able to install stripe.net for the first time.  Thank you very much!

**Comment by barnesstan** [comment]
I have VS2012 Ultimate and updating the Package Manager didn't work.
Continued to get the dependency error.
So, instead I 
1. downloaded the nupkg file to my desktop.
2. changed it to a ".zip" file
3. Opened the ZIP file and extracted the "Stripe.net.nuspec" file
4. Opened the stripe.net.nuspec file with Notepad++
5. Edited out the dependency statements for Newtonsoft for the "<group targetFramework=".NETCoreApp1.0">" and "<group targetFramework=".NETStandard1.2">"
6. Saved the nuspec file and dropped it back into the ZIP file replacing the existing one.
7. Removed the .zip extention from the nupkg file.
8. Opened my project in VS and opened Tools-Nuget package manager-Manage nuget packages for solution.
9. Clicked on the settings Button
10. Added a package source as my desktop.
11. Selected the modified nupkg file and clicked install
12. it appears to have worked without error.

Do you think I will encounter errors due to editing the stripe.net.nuspec file as above ?
Cheers s.

**Comment by jaymedavis** [comment]
It should have given you targetFramework="NETCoreApp1.0" - but netstandard 1.2 might be normal. Did you add newtonsoft.json as a reference after this?

**Comment by barnesstan** [comment]
Thanks for getting back to me... yes... I left the newtonsoft dependency under .NETFramework4.5
The XML on dependencies looked like the following:
(I have removed the < tag symbols as this editor removes everything between them automatically)

    dependencies
      group targetFramework=".NETCoreApp1.0"
        dependency id="Microsoft.NETCore.App" version="[1.0.1, )" /
      /group
      group targetFramework=".NETFramework4.5"
        dependency id="Newtonsoft.Json" version="[9.0.1, )" /
      /group
      group targetFramework=".NETStandard1.2"
        dependency id="NETStandard.Library" version="[1.6.1, )" /
      /group
    /dependencies


Cheers s.

**Comment by Drivest** [comment]
I followed barnestan recipe and it worked for me as well.

I'm in VS2012, Windows 10 and .NET framework 4.5

**Comment by jaymedavis** [comment]
thanks for commenting - i'm sure this will help others 👍

**Comment by barnesstan** [comment]
No Worries… I’ve actually gone to this forum again because I forgot how I did it the first time.

Cheers s.

**Comment by kevin192291** [comment]
Is it just me, or has anyone else been having this issue, I am totally unable to use this nuget in a Web Api project. I have tried all above suggestions, nothing has helped. I am using Visual studio 2017. Any ideas if this issue has re-occurred?

**Comment by barnesstan** [comment]
hey there, I wrote a step by step above on the 5th Feb that should get it loaded for you? What fails for you with this method? Cheers s.
