### ISSUE TITLE
String was not recognized as a valid DateTime, when trying to create a customer based on a new tokenid based on card

### ISSUE THREAD

**Issue by goodyes** [jaymedavis/stripe.net#767]
Hi, try using the sample web test I created, on
https://www.outo.es/default6.aspx

Follow the steps. View the html and js code of the web
The aspx.vb server code is: https://gist.github.com/goodyes/35dc922de492ade8648ac84029f7918b

Once the JS returns a new tokenid, the web server fails to create a customer based on new tokenid, and says "String was not recognized as a valid DateTime"

Can you test and resolve and post why ?

**Comment by goodyes** [comment]
IMPORTANT: above only happens on real webserver scenario. On localhost there is no problem

**Comment by Sbaia** [comment]
See Issue #765
I think that your problem is like mine. And is caused from CultureInfo.CurrentCulture.

I temporarily resolve the bug, setting Thread.CultureInfo.CurrentCulture = CultureInfo.InvariantCulture

If you are using Framework 4.5.2 and you use Async Methods, you should set DefaultThreadCurrentCulture, also.

**Comment by jaymedavis** [comment]
This will get fixed via #765

**Comment by goodyes** [comment]
Sbaia thank you so much, using below line on page_load event on server :
        System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture

IT WORKS !!
I justupdated the default6 sample web and you will see it works
