### ISSUE TITLE
Support for searching, or return NULL on Get?

### ISSUE THREAD

**Issue by AllenDigital** [jaymedavis/stripe.net#782]
Several times I've needed to check to see if an entity exists (such as a plan by a plan name). Currently, I run a .Get and then swallow the exception if that particular plan doesn't exist. It would be better if .Get returned a NULL rather than an exception if the entity does not exist.

Alternatively, a search style .Any() would be great so I don't need to .List every possible value to avoid swallowing an exception if an entity cannot be found using .Get

**Comment by jaymedavis** [comment]
Get for plans only supports an Id, do you mean you search the List() for the plan by name?

Regarding searching all of your plans with .any(), that's not really possible without some kind of FetchAll() logic in Stripe.net. Since Stripe requires paging the list, this isn't something I think should be implemented right now. It would be a very taxing call. I don't think it's a bad idea at all, but I think it's logic better suited for custom logic outside of the bindings. :)
