### ISSUE TITLE
Unable to specify include[]=total_count in request to StripeChargeService List

### ISSUE THREAD

**Issue by shoff** [jaymedavis/stripe.net#813]
According to the API documentation:

You can optionally request that the response include the total count of all charges that match your filters. To do so, specify include[]=total_count in your request.

Regards,
Steve Hoff

**Comment by jaymedavis** [comment]
I wrote a test and a plugin to support this functionality. However, it doesn't appear to be working. I emailed Stripe to see if I'm doing something wrong. *include[]=total_count* is exactly what I am adding to the List request.

**Comment by jaymedavis** [comment]
this turned out to be a much bigger puzzle than expected. The original List method on charges returned an IEnumerable, which isn't going to work - because Stripe returns an object that has total_count, has_more, url, etc. This class was implemented in Stripe.net as a `StripeList`. The StripeChargeService has been refactored to support returning a StripeList<StripeCharge> instead of an IEnumerable<StripeCharge>. In order to see the total count, you will pass IncludeAll to the list options (however, I'm thinking of renaming this IncludeTotalCount, since it doesn't actually include all) ...

I'm testing this now and it's up on the #813x branch. It will go live with the next release.

**Comment by shoff** [comment]
Awesome job! Thank you!

**Comment by carlospuk** [comment]
I'm not seeing this in v21.5.0 from Nuget - the `IncludeAll` option doesn't seem to be present in `ChargeListOptions`

In case anyone's having the same issue, I'm using this code to work around it for now:

`ExtraParams = new Dictionary<string, string>() { { "include[]", "total_count"} }`

**Comment by techieshark** [comment]
@remi-stripe can you point to the deprecation notice for that and/or the "include[]" parameter? 

I'm not seeing it here: https://stripe.com/docs/upgrades. 

I've [mentioned your comment](https://stackoverflow.com/questions/29960243/using-nodejs-calling-stripe-api-to-get-total-count#comment101623893_29967881) on a StackOverflow question but would love to point to whatever the most definitive source is.

**Comment by remi-stripe** [comment]
@techieshark We don't have a specific mention of this, we consider this parameter deprecated and have for a long time and we stopped supporting it in stripe-dotnet and other strongly typed libraries (java and go)

**Comment by techieshark** [comment]
Thanks @remi-stripe. 

There are a couple questions on SO about how to get total counts and the accepted answers are (as I see now) incorrect. I will update those questions to note the deprecation.

In case it helps - it is also somewhat confusing that the documentation alludes to this parameter but does not explicitly mention it is deprecated (so one might incorrectly presume that the docs just haven't covered what would otherwise look like a promising bit of info).

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/1072292/63390300-f5ce8d80-c3f1-11e9-99d6-5ef88b77861b.png">

I recently had some interactions with Stripe support about this exact issue and it took a couple weeks of back and forth emails to try to get answers, so thank you again for your quick response and for clarifying the situation.

**Comment by remi-stripe** [comment]
We haven't documented this property for a while. It does still appear in sub-lists in the responses for reasons :tm: I can't really get into but it's definitely something we hope to fix in the future!

**Comment by DoobleD** [comment]
Hi!

Is there a recommended alternative to total_count in order to get the total number of items without having to fetch the whole list with a limit = 100000 parameter?

**Comment by remi-stripe** [comment]
@DoobleD you would either paginate through the list or you would cache this information in your database instead and only list new/recent objects

**Comment by DoobleD** [comment]
Tank you @remi-stripe for this prompt answer! 

I was afraid of this answer actually. I use my own paginator and I need the full count, so my only solution would be to fetch all + store the count in database and update it for every new item, but that's kind of painful.

Well I guess I'll stick with total_count for now and I'll come back to this when it'll get removed.

**Comment by remi-stripe** [comment]
@DoobleD Can you clarify what total_count gives you if you still paginate anyway? I'm not sure I understand why each request you make would need to know the full count since you can just let the library automatically paginate for you.

Ultimately, the feature still works today but it's something we will deprecate this year. This means we'll reach out to all integrations recommending that they move off of it as we'll either remove it or return a maximum value in that field.

**Comment by DoobleD** [comment]
@remi-stripe sure! I have a pagination which shows the total number of items accross all pages, and on which the number of pages shown is calculated from that total number of items. I use this to list invoices of customers. See screenshot below (actual table rows are blured).

![show](https://user-images.githubusercontent.com/918201/76172144-f9114700-6192-11ea-8630-71d9339f6ecc.png)

But maybe there's another way of achieving this without total_count? 

Thanks for that information, I'll make sure to adapt when that happens.

**Comment by clement911** [comment]
I know it's not related to Stripe.Net specifically, but I do wish all services that support `List` also supported `Count`.

**Comment by techieshark** [comment]
@remi-stripe just out of curiosity, is there a strong reason Stripe has/is-going-to deprecate this?

I think the appeal of Stripe is a better developer experience than other systems, and given the interest here it does seem like providing a count on a list object improves the developer experience.

**Comment by remi-stripe** [comment]
@clement911 Can you clarify what `Count` would do exactly? Return the number of elements in a page? Or do you mean returning the count of all objects/elements? If it's the latter, it's not something we plan to support at least. While it'd work for many accounts, some have millions and millions of objects.

@techieshark While there's some interest in this thread, this parameter is rarely used. It has also been deprecated for well over 5 years but we kept it around for integrations that were already using it to ensure they could continue using it. We're seeing an increase in slow requests due to it though since some accounts have large numbers of objects in their account. We're also seeing integrations just still pass this parameter on every requests, which means that you're paginating trough 1M charges and requiring us to count that 1M of charges every request you make to get the next 100.

**Comment by clement911** [comment]
Return the count of all objects.
I understand it's not planned. I wish it was though. For most databases, SELECT COUNT(*) is pretty fast...

**Comment by arekbal** [comment]
@remi-stripe From the business standpoint it forces your users to build their own solutions on top of yours to just have proper list of entities they could search through(sort, pick-range, filter, count). These leads your users to rely on **Stripe** as little as possible. That is an easy way to lose customer when he/she already has the whole infrastructure ready for a switch to some other provider/s - because he was forced to do so in order to display basic 'queryable' list.

> We're also seeing integrations just still pass this parameter on every requests, which means that you're paginating trough 1M charges and requiring us to count that 1M of charges every request you make to get the next 100.
No DB expert here but...
That is what index engines, (query) caches, materialized views are for.

While returning a total count for arbitrary query (including search text, blobs, json and so on) over arbitrarily sized dataset might be an overwhelming task even for index engine, we talk *relatively well known* stuff here. Some of your queries already have to scan tables and I assume they use some sort of indices to do so anyway.

But it is your choice in the end of course. 👍

**Comment by remi-stripe** [comment]
@arekbal That's totally fair, and I do agree overall. That's one of the main reasons why this feature is still supported today even though we don't actively document it. It does cause issues though regularly, especially on larger accounts. Many integrations incorrectly send the `total_count` parameter on every page they fetch in the API, so you might be listing 1M customers, 100 at a time and on every request you ask us to count that there are 1M customers.

I'll share all your feedback internally though so please keep this coming :)

**Comment by clement911** [comment]
> Many integrations incorrectly send the total_count parameter on every page they fetch in the API, so you might be listing 1M customers, 100 at a time and on every request you ask us to count that there are 1M customers.

If there was a separate `Count` endpoint that goes along all the `List` endpoints, I believe that would help a lot.

**Comment by DoobleD** [comment]
> > Many integrations incorrectly send the total_count parameter on every page they fetch in the API, so you might be listing 1M customers, 100 at a time and on every request you ask us to count that there are 1M customers.
> 
> If there was a separate `Count` endpoint that goes along all the `List` endpoints, I believe that would help a lot.

Could be the right solution.

**Comment by arekbal** [comment]
I have some experience with designing data-grids, scroll-based data-virtualization, preparing data and optimising queries for such searches. They are - next to forms - bread and butter of backend business apps and services. These queries need to be fast.

```
Many integrations incorrectly send the total_count parameter on every page they fetch in the API, so you might be listing 1M customers, 100 at a time and on every request you ask us to count that there are 1M customers.
```
Let me address just this case, because you repeated it. 😸 
That is effectively 2 queries. One is about paging, another one is about the count. You can probably make them one in your lower layer(sql, whatever). but for cache purposes they are separate queries. That second one is same with each request - could easily be cached and return same value for each, subsequent page request. 

Also, anoher example of possible optimization would be: if you know they do paging for a large 'limit' (like with auto-paging **feature**). It would be _cheaper_, to do a one bigger query (instead of a one per http request) and then return parts in requests (to still keep it in reasonable http chunks).


Obviously there are other caveats as how to approach new records happening in the meantime (then we talk _beloved_ data-streams then), but let's leave it for some other time. ;)

> If there was a separate Count endpoint that goes along all the List endpoints, I believe that would help a lot.
@clement911  That is simple therefore I like it, but it would have it's own problems: 
1. Some integrations might still use it incorrectly. Because you want these devs to be aware of distinction between: having different filters applied means you have to repeat count, while if you only do paging - don't repeat Count(q).
2. If it is not part of single request, then it cannot be optimised further away in pipeline (like single sql query to grab both results). 
3. It is also not part of a single transaction so making sure these 2 reads represent same table state is harder.

**Comment by DoobleD** [comment]
Hi folks,

I got an email from Stripe stating they will remove the total_count option on May 26. Below is the full email.

> Hello,
> 
> My name is Thomas and I'm a support engineer at Stripe. We recently noticed that a number of API requests to Stripe made by your integration on the account postale.io have been quite slow. This issue is affecting requests to retrieve lists of Invoices from the Stripe API.
> 
> Let me start by clarifying that this doesn't impact your ability to charge your customers. However, these requests do put some undue burden on both our systems and yours and often fail or timeout. I wanted to discuss this issue so that you, or your developers, can work on a fix on your end.
> 
> These requests are slow because they use a deprecated and undocumented feature. This is due to your code requesting the total number of objects in the list by passing the total_count parameter. This is a feature that we have deprecated over 5 years ago now and actively discourage any integration to rely on. It still works, to avoid breaking integrations, but we do know it regularly causes issues like this.
> 
> Since you're already actively paginating through the list, you shouldn't need to get the total count of objects at the same time. Instead of passing include[]=total_count or count, you should simply pass limit=100 and paginate through the list until has_more is returned as false.
> 
> It is likely that other parts of your integration are also passing the total_count parameter today. I’d recommend changing those calls at the same time to ensure that you never use total_count.
> 
> We are planning to remove this feature on May 26. Would you be able to investigate this on your end and make the relevant changes to your code to stop requesting this feature by then?
> 
> Please let me know if you have any questions!
> All the best,
> Thomas

I replied with a link to this page, we'll see if that can help this issue!

**Comment by remi-stripe** [comment]
Just to clarify: we're removing it specifically on the List Invoices endpoint, not all APIs for now (though it's still something we plan to remove entirely). That endpoint is the one seeing the least usage (less than 50 integrations overall are passing that parameter, most of those do this once a month or less). It's also the endpoint that is causing the most operational issues with recurring timeouts making the user experience worse overall.
