### ISSUE TITLE
Getting started with Stripe.Net

### ISSUE THREAD

**Issue by saboehnke** [jaymedavis/stripe.net#892]
I guess I am just a little confused on how to go about implementing this .Net wrapper. I basically need to all a user to subscribe to my service on their account page. I already have a subscribe button there. Going through the Stripe documentation it looks like I need to setup a link to stripe to allow the user to sign into their Stripe account or create one (for a standalone account I mean). Is this handled the same way with this wrapper?

I'm just having problems figuring out how to start with that process and to get their customer ID in order to create a subscription for them. Any tips?

**Comment by remi-stripe** [comment]
@saboehnke If you're only charging customers for your service, you wouldn't need to use Stripe Connect or Standard/Standalone accounts. You simply want to collect their card details securely so the steps would look like this:

1. Collect their card details client-side securely with [Stripe Checkout](https://stripe.com/docs/checkout) or [Stripe Elements](https://stripe.com/docs/elements).
2. You get a card token `tok_XXXX` back that you send to your server.
3. Server-side, you use that token to [create a customer](https://github.com/jaymedavis/stripe.net#creating-a-customer) and save their card.
4. You [subscribe](https://github.com/jaymedavis/stripe.net#creating-a-subscription) the customer to your plan so that they get charged the expected amount now and on a recurring basis.

You can learn more about subscriptions in our official documentation [here](https://stripe.com/docs/subscriptions/quickstart)

**Comment by saboehnke** [comment]
@remi-stripe That is great. But I also need to allow subscribing users to accept payments from their customers and when they get a payment from one of their customers I take a small percentage. I need connect for this correct?

**Comment by remi-stripe** [comment]
@saboehnke ah yes in that case you do need Stripe Connect. Each seller would have their own Standard/Standalone account and would connect their account to your platform via OAuth.

I'd recommend reading the documentation around Stripe Connect first and reaching out to Stripe support if you have more questions as this will be more about the product and not about Stripe.net itself.

The doc to start is here: https://stripe.com/docs/connect/standard-accounts
