### ISSUE TITLE
Issues supporting Stripe Connect

### ISSUE THREAD

**Issue by NeoHub** [jaymedavis/stripe.net#912]
Hi @jaymedavis! Currently I want to implement Stripe Connect using your library, but I'm not sure if it's currently supporting all features. I don't see a way to specify the type of the account that I want to create (in my case Custom accounts), so I don't know if I can achieve this creating a "managed account". Also I see in the stripe documentation that the name was changed from "Managed" to "Custom" in May 2017. Will it work anyways? Can you guide me a little through the process? Thanks!

**Comment by remi-stripe** [comment]
@NeoHub The naming change happened behind a new API version which was released on [2017-05-25](https://stripe.com/docs/upgrades#2017-05-25). At the moment, Stripe.net only supports the version before that. At the time, Custom accounts were called Managed accounts.

There's a PR in progress to support the latest API version [here](https://github.com/jaymedavis/stripe.net/pull/898) but in the meantime, you can use the current version and simply pass `Managed=True` instead of `Type="custom"` and it will work as expected.

**Comment by NeoHub** [comment]
Thanks! Also I have a question about the Identity verification process. It seems that `StripeAccountCreateOptions` doesn't have properties like date of birth and business type. Is there a way to collect that information?

**Comment by remi-stripe** [comment]
@NeoHub This would live under the `LegalEntity` on the `StripeAccountCreateOptions` for example. You can see a basic example in the tests [here](https://github.com/jaymedavis/stripe.net/blob/f0a8f6c691a96ab085842c7526f9fdceec666eaa/src/Stripe.net.Tests/account/when_creating_an_account_with_a_legal_entity.cs#L23)
