### ISSUE TITLE
MetaData does not show up on the Destination account( Stripe connect)

### ISSUE THREAD

**Issue by varunbabu008** [jaymedavis/stripe.net#938]
While creating a charge(stripe connect destination charges) I noticed that the meta data parameter is not showing up on the destination account dashboard. 

Ideally the MetaData(Highlighted below) should show up on the Destination account as well. Currently it is showing up on the platform account dashboard and not on the destination account on which charges are made.

` var newCharge = new StripeChargeCreateOptions()
                {

                    Amount = amt,
                    Currency = "AUD",
                    Destination = “xxxxxx", 
                    DestinationAmount = shipping + gstshipping,
                    Metadata = myDict // Dictionary(key value pairs)
                
                };
`
Is there any work around for this

**Comment by remi-stripe** [comment]
@varunbabu008 That's expected behaviour, the metadata live on the Charge in the platform not on the corresponding payment created on the connected account.

This is not a bug with the library so github issues is not the best place to discuss this. The idea is that you will Create the Destination charge and get a Charge object back with a `transfer` property for a `Transfer` id `tr_XXXX` that you can expand. This Transfer object will have a `destination_payment` id `py_XXX`. You can then use that id to retrieve the payment (like a charge) on the connected id and update it to the right metadata.

If you have follow up questions, it's best to reach out to our support team: https://support.stripe.com/email

**Comment by amos-o** [comment]
@remi-stripe You said:

> You can then use that id to retrieve the payment (like a charge)

Which endpoint would I use to do that? Because as of now, the destination payment ID I get is of the format `py-xxxx` which is not a Charge or a Payout so I am stuck there.

**Comment by remi-stripe** [comment]
@amos-o a `py_XXXX` is just a normal Charge. So you would use the Retrieve Charge [API](https://stripe.com/docs/api#retrieve_charge) and using the `Stripe-Account` [header](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header) which in stripe-dotnet is set via [RequestOptions](https://github.com/stripe/stripe-dotnet#request-options)

**Comment by amos-o** [comment]
I was missing the `Stripe-Account` header. Thank you @remi-stripe.

**Comment by mckravchyk** [comment]
I came here by search results. This is what I did to automatically sync the metadata from main charge to connected charge:
- Listen to `charge.succeeded`
- The charge object will contain `application_fee` (id) and `metadata`
- Retrieve application_fee object
- application_fee should contain the connected account id (`account`) and connected charge id (`charge`)
- Now you can update the connected charge with metadata
